---
- name: Verify
  hosts: all
  become: true
  roles:
    - geerlingguy.git
  tasks:
    - name: install cinc-auditor
      shell: "wget -O - -L https://omnitruck.cinc.sh/install.sh | sudo bash -s -- -P cinc-auditor -v 4"

    - name: Execute cinc-auditor tests
      command: "cinc-auditor exec --no-show-progress --no-color --no-distinct-exit https://github.com/dev-sec/linux-baseline.git"
      register: test_results
      changed_when: false
      ignore_errors: true

    - name: Display details about the cinc-auditor results
      debug:
        msg: "{{ test_results.stdout_lines }}"

    - name: Fail when tests fail
      fail:
        msg: "Inspec failed to validate"
      when: test_results.rc != 0
