- name: prepare playbook for kitchen testing "ansible-nginx-hardening" with custom settings
  become: true
  hosts: all
  tasks:
    - apt_repository:
        repo: "deb http://ftp.debian.org/debian jessie-backports main"
        state: present
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '8'

    - set_fact:
        nginx_default_release: "jessie-backports"
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '8'

    - package:
        name:
        - "systemd"
        - "python3-apt"
        update_cache: true
      ignore_errors: true
